let cfg=null, appOptions=[], recommendations=[], backups=[], adminPage=0, adminSection='overview', adminTileQuery='', adminTileVisibility='all', adminSelectedTileIds=new Set(), pinCallback=null, pinReturnFocus=null;
let features={shutdownAvailable:false,speechFeedbackAvailable:false};
let timerPollInterval=null, lastTimerStatus={};
let availabilityPollInterval=null, availabilityStatus={profileAllowed:true,blockedTileIds:[]}, selectedAppScheduleId='';
let updateAvailable=false, remoteVersion='';
let browserOptions=[];
let appCatalogState='loading', recommendationState='loading', browserCatalogState='loading', backupState='loading';
let activityState='loading', activityData={recordCount:0,totalDurationSeconds:0,records:[],profiles:[]};
let bootstrapPromise=null;
let profilePickerReturnFocus=null;
const PROFILE_TEXT={
  de:{manageHint:'Jedes Kind erhält einen eigenen Startbildschirm. Globale Eltern- und System-Einstellungen gelten weiterhin für alle.',listTitle:'Kinderprofile',editorTitle:'Aktives Profil',name:'Name',avatar:'Avatar',launcherTitle:'Titel auf dem Startbildschirm',createTitle:'Profil hinzufügen',create:'Hinzufügen',select:'Auswählen',active:'Aktiv',remove:'Löschen',removeConfirm:'Dieses Kinderprofil und seine Einstellungen wirklich löschen?',pickerTitle:'Wer möchte starten?',pickerHint:'Ein Wechsel zu einem anderen Profil muss von einem Elternteil bestätigt werden.',close:'Schließen',error:'Das Profil konnte nicht geändert werden.',nameRequired:'Bitte einen Namen eingeben.',namePlaceholder:'Name des Kindes',avatarPlaceholder:'Emoji, z. B. 🚀'},
  en:{manageHint:'Each child gets a separate home screen. Global Parent and system settings continue to apply to everyone.',listTitle:'Child profiles',editorTitle:'Active profile',name:'Name',avatar:'Avatar',launcherTitle:'Home screen title',createTitle:'Add profile',create:'Add',select:'Select',active:'Active',remove:'Delete',removeConfirm:'Delete this child profile and its settings?',pickerTitle:'Who wants to start?',pickerHint:'Switching to another profile must be confirmed by a parent.',close:'Close',error:'The profile could not be changed.',nameRequired:'Please enter a name.',namePlaceholder:"Child's name",avatarPlaceholder:'Emoji, e.g. 🚀'}
};
let uiText = {
  adminTitle: {{JSON_ADMIN_TITLE}},
  adminNavLabel: {{JSON_ADMIN_NAV_LABEL}},
  adminOverview: {{JSON_ADMIN_OVERVIEW}},
  adminChildren: {{JSON_ADMIN_CHILDREN}},
  adminAppsMedia: {{JSON_ADMIN_APPS_MEDIA}},
  adminScreenTime: {{JSON_ADMIN_SCREEN_TIME}},
  adminAppearance: {{JSON_ADMIN_APPEARANCE}},
  adminSystem: {{JSON_ADMIN_SYSTEM}},
  appSearchLabel: {{JSON_APP_SEARCH_LABEL}},
  appFilterLabel: {{JSON_APP_FILTER_LABEL}},
  appFilterAll: {{JSON_APP_FILTER_ALL}},
  appFilterVisible: {{JSON_APP_FILTER_VISIBLE}},
  appFilterHidden: {{JSON_APP_FILTER_HIDDEN}},
  appFilterEmpty: {{JSON_APP_FILTER_EMPTY}},
  appFilterCount: {{JSON_APP_FILTER_COUNT}},
  appBulkActions: {{JSON_APP_BULK_ACTIONS}},
  appBulkSelectAll: {{JSON_APP_BULK_SELECT_ALL}},
  appBulkSelected: {{JSON_APP_BULK_SELECTED}},
  appBulkShow: {{JSON_APP_BULK_SHOW}},
  appBulkHide: {{JSON_APP_BULK_HIDE}},
  appBulkDelete: {{JSON_APP_BULK_DELETE}},
  appBulkDeleteConfirm: {{JSON_APP_BULK_DELETE_CONFIRM}},
  appSelectTile: {{JSON_APP_SELECT_TILE}},
  confirmTitle: {{JSON_CONFIRM_TITLE}},
  confirmCancel: {{JSON_CONFIRM_CANCEL}},
  confirmContinue: {{JSON_CONFIRM_CONTINUE}},
  retry: {{JSON_RETRY}},
  startupLoading: {{JSON_STARTUP_LOADING}},
  startupErrorTitle: {{JSON_STARTUP_ERROR_TITLE}},
  startupError: {{JSON_STARTUP_ERROR}},
  saveLoading: {{JSON_SAVE_LOADING}},
  saveError: {{JSON_SAVE_ERROR}},
  appCatalogLoading: {{JSON_APP_CATALOG_LOADING}},
  appCatalogEmpty: {{JSON_APP_CATALOG_EMPTY}},
  appCatalogError: {{JSON_APP_CATALOG_ERROR}},
  browserCatalogLoading: {{JSON_BROWSER_CATALOG_LOADING}},
  browserCatalogEmpty: {{JSON_BROWSER_CATALOG_EMPTY}},
  browserCatalogError: {{JSON_BROWSER_CATALOG_ERROR}},
  recommendationsLoading: {{JSON_RECOMMENDATIONS_LOADING}},
  recommendationsEmpty: {{JSON_RECOMMENDATIONS_EMPTY}},
  recommendationsError: {{JSON_RECOMMENDATIONS_ERROR}},
  placeholderTitle: {{JSON_PLACEHOLDER_TITLE}},
  placeholderParentLabel: {{JSON_PLACEHOLDER_PARENT_LABEL}},
  placeholderExitLabel: {{JSON_PLACEHOLDER_EXIT_LABEL}},
  addTile: {{JSON_ADD_TILE}},
  back: {{JSON_BACK}},
  save: {{JSON_SAVE}},
  visible: {{JSON_VISIBLE}},
  specialMedia: {{JSON_SPECIAL_MEDIA}},
  noApp: {{JSON_NO_APP}},
  customCmd: {{JSON_CUSTOM_CMD}},
  moveUp: {{JSON_MOVE_UP}},
  moveDown: {{JSON_MOVE_DOWN}},
  delete: {{JSON_DELETE}},
  newTile: {{JSON_NEW_TILE}},
  pinTitle: {{JSON_PIN_TITLE}},
  pinPlaceholder: {{JSON_PIN_PLACEHOLDER}},
  pinWrong: {{JSON_PIN_WRONG}},
  pinSet: {{JSON_PIN_SET}},
  pinChange: {{JSON_PIN_CHANGE}},
  pinRemove: {{JSON_PIN_REMOVE}},
  pinConfirm: {{JSON_PIN_CONFIRM}},
  pinMismatch: {{JSON_PIN_MISMATCH}},
  pinSaved: {{JSON_PIN_SAVED}},
  pinRemoved: {{JSON_PIN_REMOVED}},
  adminPagePrev: {{JSON_ADMIN_PAGE_PREV}},
  adminPageNext: {{JSON_ADMIN_PAGE_NEXT}},
  updateCheck: {{JSON_UPDATE_CHECK}},
  updateAvailable: {{JSON_UPDATE_AVAILABLE}},
  updateUpToDate: {{JSON_UPDATE_UP_TO_DATE}},
  updateLoading: {{JSON_UPDATE_LOADING}},
  updateError: {{JSON_UPDATE_ERROR}},
  versionLabel: {{JSON_VERSION_LABEL}},
  updateNow: {{JSON_UPDATE_NOW}},
  updateProgress: {{JSON_UPDATE_PROGRESS}},
  updateConfirm: {{JSON_UPDATE_CONFIRM}},
  recommendedTitle: {{JSON_RECOMMENDED_TITLE}},
  appBrowserTitle: {{JSON_APP_BROWSER_TITLE}},
  browserPage: {{JSON_BROWSER_PAGE}},
  webModeEmbedded: {{JSON_WEB_MODE_EMBEDDED}},
  webModeExternal: {{JSON_WEB_MODE_EXTERNAL}},
  browserAllowlistLabel: {{JSON_BROWSER_ALLOWLIST_LABEL}},
  browserBoundaryEmbedded: {{JSON_BROWSER_BOUNDARY_EMBEDDED}},
  browserBoundaryExternal: {{JSON_BROWSER_BOUNDARY_EXTERNAL}},
  browserAllowlistInvalid: {{JSON_BROWSER_ALLOWLIST_INVALID}},
  install: {{JSON_INSTALL}},
  added: {{JSON_ADDED}},
  installed: {{JSON_INSTALLED}},
  notInstalled: {{JSON_NOT_INSTALLED}},
  copyCommand: {{JSON_COPY_COMMAND}},
  commandCopied: {{JSON_COMMAND_COPIED}},
  installStarted: {{JSON_INSTALL_STARTED}},
  installManual: {{JSON_INSTALL_MANUAL}},
  close: {{JSON_CLOSE}},
  exportConfig: {{JSON_EXPORT_CONFIG}},
  importConfig: {{JSON_IMPORT_CONFIG}},
  exportDiagnostics: {{JSON_EXPORT_DIAGNOSTICS}},
  importSuccess: {{JSON_IMPORT_SUCCESS}},
  importError: {{JSON_IMPORT_ERROR}},
  invalidConfig: {{JSON_INVALID_CONFIG}},
  importConfirm: {{JSON_IMPORT_CONFIRM}},
  startingApp: {{JSON_STARTING_APP}},
  startedApp: {{JSON_STARTED_APP}},
  feedbackOptions: {{JSON_FEEDBACK_OPTIONS}},
  soundFeedback: {{JSON_SOUND_FEEDBACK}},
  speechFeedback: {{JSON_SPEECH_FEEDBACK}},
  speechAvailable: {{JSON_SPEECH_AVAILABLE}},
  speechUnavailable: {{JSON_SPEECH_UNAVAILABLE}},
  feedbackHint: {{JSON_FEEDBACK_HINT}},
  accessibilityOptions: {{JSON_ACCESSIBILITY_OPTIONS}},
  accessibilityLargeText: {{JSON_ACCESSIBILITY_LARGE_TEXT}},
  accessibilityHighContrast: {{JSON_ACCESSIBILITY_HIGH_CONTRAST}},
  accessibilityReducedMotion: {{JSON_ACCESSIBILITY_REDUCED_MOTION}},
  accessibilityKeyboardFocus: {{JSON_ACCESSIBILITY_KEYBOARD_FOCUS}},
  accessibilityHint: {{JSON_ACCESSIBILITY_HINT}},
  emptyStateEmoji: {{JSON_EMPTY_STATE_EMOJI}},
  emptyStateText: {{JSON_EMPTY_STATE_TEXT}},
  previewTitle: {{JSON_PREVIEW_TITLE}},
  timerLabel: {{JSON_TIMER_LABEL}},
  timerOff: {{JSON_TIMER_OFF}},
  timerMinutes15: {{JSON_TIMER_15}},
  timerMinutes30: {{JSON_TIMER_30}},
  timerMinutes60: {{JSON_TIMER_60}},
  timerMinutes: {{JSON_TIMER_MINUTES}},
  timerCustom: {{JSON_TIMER_CUSTOM}},
  timerStart: {{JSON_TIMER_START}},
  timerStop: {{JSON_TIMER_STOP}},
  timerActive: {{JSON_TIMER_ACTIVE}},
  timerExpired: {{JSON_TIMER_EXPIRED}},
  timerRemaining: {{JSON_TIMER_REMAINING}},
  timerWarningTitle: {{JSON_TIMER_WARNING_TITLE}},
  timerWarningText: {{JSON_TIMER_WARNING_TEXT}},
  timerEnterPin: {{JSON_TIMER_ENTER_PIN}},
  timerExtend: {{JSON_TIMER_EXTEND}},
  timerExit: {{JSON_TIMER_EXIT}},
  timerWrongPin: {{JSON_TIMER_WRONG_PIN}},
  timerExtended: {{JSON_TIMER_EXTENDED}},
  weeklyScheduleTitle: {{JSON_SCHEDULE_WEEKLY_TITLE}},
  weeklyScheduleHint: {{JSON_SCHEDULE_WEEKLY_HINT}},
  scheduleEnabled: {{JSON_SCHEDULE_ENABLED}},
  appScheduleTitle: {{JSON_SCHEDULE_APP_TITLE}},
  appScheduleHint: {{JSON_SCHEDULE_APP_HINT}},
  scheduleSelectApp: {{JSON_SCHEDULE_SELECT_APP}},
  scheduleAddWindow: {{JSON_SCHEDULE_ADD_WINDOW}},
  scheduleRemoveWindow: {{JSON_SCHEDULE_REMOVE_WINDOW}},
  scheduleStart: {{JSON_SCHEDULE_START}},
  scheduleEnd: {{JSON_SCHEDULE_END}},
  scheduleClearApp: {{JSON_SCHEDULE_CLEAR_APP}},
  scheduleNoWindows: {{JSON_SCHEDULE_NO_WINDOWS}},
  scheduleBlockedTitle: {{JSON_SCHEDULE_BLOCKED_TITLE}},
  scheduleProfileBlocked: {{JSON_SCHEDULE_PROFILE_BLOCKED}},
  scheduleAppBlocked: {{JSON_SCHEDULE_APP_BLOCKED}},
  scheduleOpenParents: {{JSON_SCHEDULE_OPEN_PARENTS}},
  weekdayMonday: {{JSON_WEEKDAY_MONDAY}},
  weekdayTuesday: {{JSON_WEEKDAY_TUESDAY}},
  weekdayWednesday: {{JSON_WEEKDAY_WEDNESDAY}},
  weekdayThursday: {{JSON_WEEKDAY_THURSDAY}},
  weekdayFriday: {{JSON_WEEKDAY_FRIDAY}},
  weekdaySaturday: {{JSON_WEEKDAY_SATURDAY}},
  weekdaySunday: {{JSON_WEEKDAY_SUNDAY}},
  backupTitle: {{JSON_BACKUP_TITLE}},
  backupRestore: {{JSON_BACKUP_RESTORE}},
  backupEmpty: {{JSON_BACKUP_EMPTY}},
  backupLoading: {{JSON_BACKUP_LOADING}},
  backupLoadError: {{JSON_BACKUP_LOAD_ERROR}},
  backupRestoring: {{JSON_BACKUP_RESTORING}},
  backupConfirm: {{JSON_BACKUP_CONFIRM}},
  backupSuccess: {{JSON_BACKUP_SUCCESS}},
  backupError: {{JSON_BACKUP_ERROR}},
  backupInstaller: {{JSON_BACKUP_INSTALLER}},
  backupPreRestore: {{JSON_BACKUP_PRE_RESTORE}},
  backupPinPreserved: {{JSON_BACKUP_PIN_PRESERVED}},
  activityTitle: {{JSON_ACTIVITY_TITLE}},
  activityHint: {{JSON_ACTIVITY_HINT}},
  activityEnabled: {{JSON_ACTIVITY_ENABLED}},
  activityEnabledStatus: {{JSON_ACTIVITY_ENABLED_STATUS}},
  activityDisabledStatus: {{JSON_ACTIVITY_DISABLED_STATUS}},
  activityTime: {{JSON_ACTIVITY_TIME}},
  activityLaunches: {{JSON_ACTIVITY_LAUNCHES}},
  activityRecent: {{JSON_ACTIVITY_RECENT}},
  activityEmpty: {{JSON_ACTIVITY_EMPTY}},
  activityLoading: {{JSON_ACTIVITY_LOADING}},
  activityError: {{JSON_ACTIVITY_ERROR}},
  activityExport: {{JSON_ACTIVITY_EXPORT}},
  activityClear: {{JSON_ACTIVITY_CLEAR}},
  activityClearConfirm: {{JSON_ACTIVITY_CLEAR_CONFIRM}},
  activityClearSuccess: {{JSON_ACTIVITY_CLEAR_SUCCESS}},
  activityClearError: {{JSON_ACTIVITY_CLEAR_ERROR}},
  activityUnknownProfile: {{JSON_ACTIVITY_UNKNOWN_PROFILE}},
  activityUnknownApp: {{JSON_ACTIVITY_UNKNOWN_APP}},
  activityLessMinute: {{JSON_ACTIVITY_LESS_MINUTE}},
  activityMinutes: {{JSON_ACTIVITY_MINUTES}},
  activityHoursMinutes: {{JSON_ACTIVITY_HOURS_MINUTES}}
};

function clearUiState(element){
  if(!element) return;
  element.replaceChildren();
  element.className='ui-state';
  element.hidden=true;
  element.removeAttribute('aria-busy');
  element.setAttribute('role','status');
}

function renderUiState(element,state,message,retryAction=null){
  if(!element) return;
  element.replaceChildren();
  element.className='ui-state ui-state-'+state;
  element.hidden=false;
  element.setAttribute('role',state==='error'?'alert':'status');
  element.setAttribute('aria-busy',state==='loading'?'true':'false');
  const text=document.createElement('span');
  text.className='ui-state-message';
  text.textContent=message;
  element.appendChild(text);
  if(retryAction){
    const retry=document.createElement('button');
    retry.type='button';
    retry.className='smallbtn ui-state-retry';
    setIconLabel(retry,'refresh',uiText.retry);
    retry.onclick=retryAction;
    element.appendChild(retry);
  }
}
